from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol, runtime_checkable

from tools.finops.models import UsageRecord

from .entities import AgentEvent, Document, ERPRecord, Extraction, HumanReview, Job


class PersistenceConfigurationError(RuntimeError):
    pass


@runtime_checkable
class PersistenceStore(Protocol):
    path: Path
    backup_path: Path
    jobs: dict[str, Job]
    documents: dict[str, Document]
    extractions: dict[str, Extraction]
    events: dict[str, AgentEvent]
    human_reviews: dict[str, HumanReview]
    erp_records: dict[str, ERPRecord]
    finops_usage_records: dict[str, UsageRecord]

    def next_id(self, prefix: str) -> str: ...
    def save(self) -> None: ...
    def load(self) -> None: ...
    def reset(self) -> None: ...
    def add_job(self, job: Job) -> Job: ...
    def add_document(self, document: Document) -> Document: ...
    def add_extraction(self, extraction: Extraction) -> Extraction: ...
    def add_event(self, event: AgentEvent) -> AgentEvent: ...
    def add_human_review(self, review: HumanReview) -> HumanReview: ...
    def add_erp_record(self, record: ERPRecord) -> ERPRecord: ...
    def add_finops_usage_record(self, record: UsageRecord) -> UsageRecord: ...
    def update_job(self, job_id: str, **changes: Any) -> Job: ...
    def update_document(self, document_id: str, **changes: Any) -> Document: ...
    def documents_for_job(self, job_id: str) -> list[Document]: ...
    def events_for_job(self, job_id: str) -> list[AgentEvent]: ...
    def extraction_for_document(self, document_id: str) -> Extraction | None: ...
    def reviews_for_job(self, job_id: str) -> list[HumanReview]: ...
    def erp_records_for_job(self, job_id: str) -> list[ERPRecord]: ...
    def find_registered_invoice(
        self,
        cnpj: str | None = None,
        invoice_number: str | None = None,
        *,
        country_code: str | None = None,
        tax_id: str | None = None,
        normalized_tax_id: str | None = None,
        normalized_invoice_number: str | None = None,
    ) -> ERPRecord | None: ...
    def open_human_reviews(self) -> list[HumanReview]: ...
    def object_path_for_document(self, document: Document) -> str: ...
    def store_document_bytes(self, document: Document, content: bytes, content_type: str = "application/pdf") -> str: ...
    def document_object_metadata(self, document: Document) -> dict[str, Any]: ...
    def read_document_bytes(self, document: Document) -> bytes: ...
    def delete_document_object(self, document: Document) -> None: ...
